### PR TITLE
v1.0.1.1: require base >= 4.11, CI for GHC 8.4-9.12 (fixes #16)

### LINKED ISSUE #16: Diff-1.0.1 fails to build with GHC 8.2
https://github.com/BNFC/bnfc/actions/runs/11686979499/job/32544018443?pr=485#step:17:70
```
Building library for Diff-1.0.1...
...
src/Data/Algorithm/DiffContext.hs:137:17: error:
    • Variable not in scope: (<>) :: t7 -> Doc -> Doc
    • Perhaps you meant one of these:
        ‘<=’ (imported from Prelude), ‘>’ (imported from Prelude),
        ‘<’ (imported from Prelude)
      Perhaps you want to add ‘<>’ to the import list in the import of
      ‘Text.PrettyPrint’ (src/Data/Algorithm/DiffContext.hs:27:1-48).
    |
137 |     hcat . map (<> text "\n") $ (text "--- " <> old :
    |                 ^^
...
```
Perhaps you meant to set the lower bound of base to `base >= 4.11`?
https://github.com/seereason/Diff/blob/c99d861326ab349e05ea67c17cdfacda1b8fbce8/Diff.cabal#L15
https://github.com/seereason/Diff/blob/c99d861326ab349e05ea67c17cdfacda1b8fbce8/Diff.cabal#L24

Your CI looks broken, maybe that is not a good state of affairs: https://github.com/seereason/Diff/actions/runs/11652452541

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #16: package no longer builds with base < 4.11 due to Semigroup revolution

I also updated the CI and make the testsuite depend on `Diff` in the cabal file.

### CODE REVIEW

**Comment by ddssff** [comment]
Thanks

**Comment by andreasabel** [comment]
I revised 1.0 and 1.0.1 on Hackage to fix the base lower bound.

2024-11-06T20:51:50Z  	AndreasAbel	  [Diff-1.0-r1](https://hackage.haskell.org/package/Diff-1.0/revisions)
2024-11-06T20:49:14Z  	AndreasAbel	  [Diff-1.0.1-r1](https://hackage.haskell.org/package/Diff-1.0.1/revisions)
